### ISSUE TITLE
Import of SSX Map wavefront obj files

### ISSUE THREAD

**Issue by SsxMapper** [GlitcherOG/SSX-Tricky-PS2-Level-Editor#1]
Would this project I just made https://github.com/SsxMapper/SSXandTrickyMapExtractor be useful for getting the curved surface parts of the game maps into the level editor?  Or do you have another way for that?

**Comment by GlitcherOG** [comment]
Where were you 2 months ago? lol. We already figured out a method to load the patch data and convert it to proper xyz cords so we could make changes to it. https://github.com/GlitcherOG/SSX-Collection-Multitool contains the code this editor used to load pbd data and convert it to json so its more readable by more programs (And done in an alt program to reduce lag in the editor). While not the most readable stuff it should help you with how you are loading some types of data as well. since we have now got it to export meshes, instance data and some material data

![unknown](https://user-images.githubusercontent.com/54088472/197647996-5c03fdae-e358-4aba-99a6-6acb8cad45fb.png)

**Comment by SsxMapper** [comment]
Haha I only figured it out 1 month ago! That looks awesome what you have done, I will take a look.

**Comment by GlitcherOG** [comment]
I would also recommend if you aren't already to join the ssx and ssx modding discord since we have people figure out stuff all the time and out love any contributions
https://discord.gg/Qkn3NPKZGu
https://discord.com/invite/3AMzANMK

**Comment by SsxMapper** [comment]
Could you please send me an invite to the discord server again? It expired,
sorry my bad.

**Comment by GlitcherOG** [comment]
These should work, it was an autobot thing that nuked you
https://discord.gg/Qkn3NPKZGu
https://discord.gg/jtZSjBv

**Comment by SsxMapper** [comment]
Thanks managed to join one, but SSX modder's cave gives an error:
[image: image.png]

**Comment by GlitcherOG** [comment]
https://discord.gg/tTYX3ynB
Try this one fresh link
